In [90]:
import numpy as np

## DataTypes & Attributes

In [91]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [92]:
type(a1)

numpy.ndarray

In [93]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [94]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [95]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [96]:
a1.shape

(3,)

In [97]:
a2.shape

(2, 3)

In [98]:
a3.shape

(2, 3, 3)

In [99]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [100]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [101]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [102]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [103]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creatting Arrays

In [104]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [105]:
sample_array.dtype

dtype('int64')

In [106]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [107]:
ones.dtype

dtype('float64')

In [108]:
type(ones)

numpy.ndarray

In [109]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [110]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [111]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [112]:
random_array.size

15

In [113]:
random_array.shape

(3, 5)

In [114]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ]])

In [115]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677]])

In [116]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [117]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Matrices

In [118]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a1

array([1, 2, 3])

In [120]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [121]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [122]:
a1[0]

1

In [123]:
a2[0]

array([1. , 2. , 3.3])

In [124]:
a3.shape

(2, 3, 3)

In [125]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
a2[1]

array([4. , 5. , 6.5])

In [127]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [128]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [129]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [130]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4. Manipulating & Comparing Arrays

In [131]:
a1

array([1, 2, 3])

In [132]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [133]:
a1 + ones

array([2., 3., 4.])

In [134]:
a1 - ones

array([0., 1., 2.])

In [135]:
a1 * ones

array([1., 2., 3.])

In [136]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [137]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [138]:
# How can you reshape a2 to be compatible with a3?

In [139]:
a1 / ones

array([1., 2., 3.])

In [140]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [141]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [142]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [143]:
a1 % 2 

array([1, 0, 1])

In [144]:
a1 / 2

array([0.5, 1. , 1.5])

In [145]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [146]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Aggregation = performing the same operation on a number of things

In [147]:
listy_list = [1,2,3]
type(listy_list)

list

In [148]:
sum(listy_list)

6

In [149]:
type(a1)

numpy.ndarray

In [150]:
np.sum(a1)

6

Use Python't methods (sum()) on Python datatypes and use
Use NumPy's methods (np.sum()) on NumPy arrays

In [151]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [152]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [153]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

7 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.5 µs ± 63.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [154]:
np.mean(a2)

3.6333333333333333

In [155]:
np.max(a2)

6.5

In [156]:
np.min(a2)

1.0

In [157]:
# Standard deviation = squareroot of variance

np.std(a2)

1.8226964152656422

In [158]:
# Variance = measure of the average degree to which each number is different  from the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [159]:
# Demo of std and va
high_var_array = np.array([1, 100, 200, 300, 400, 50000])
low_var_array = np.array([2,4,5,8,10])

In [160]:
np.var(high_var_array), np.var(low_var_array)

(344463833.47222227, 8.16)

In [161]:
np.std(high_var_array), np.std(low_var_array)

(18559.736891244505, 2.85657137141714)

In [162]:
np.mean(high_var_array), np.mean(low_var_array)

(8500.166666666666, 5.8)

Reshaping and Transposing

In [163]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [164]:
a2.shape

(2, 3)

In [165]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [166]:
a3.shape

(2, 3, 3)

In [167]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2_reshape = a2.reshape(2,3,1)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
# Transpose = switches the axis'
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [ ]:
a3.T.shape

(3, 3, 2)

## Dot Product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [ ]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [ ]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [ ]:
# Element-wise multipliocation (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
# Dot Product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [ ]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [ ]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Examples (Nut Butter Sales)

In [ ]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [169]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=['Mon', 'Tues', 'Wed','Thrus','Fri'], 
                            columns = ['Almond Butter', 'Peanut Butter', 'Cashew Butter'] )
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thrus              4              6             12
Fri                1              6              7

In [ ]:
# Create Prices Array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [170]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [ ]:
# Shapes aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [171]:
# Create daily_sales
daily_sales = butter_prices.dot(weekly_sales.T)

In [172]:
daily_sales

Mon  Tues  Wed  Thrus  Fri
Price  240   138  458    232  142

In [173]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thrus              4              6             12        232
Fri                1              6              7        142