In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creatting Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[8, 2, 3, 5, 7],
       [7, 9, 7, 8, 8],
       [5, 7, 8, 0, 0]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.98095047, 0.40741715, 0.94611626],
       [0.18318746, 0.36488444, 0.40777421],
       [0.89820137, 0.705901  , 0.31998597],
       [0.69150177, 0.73347684, 0.47165928],
       [0.56088323, 0.21289872, 0.53691705]])

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.04642328, 0.36872036, 0.73369334],
       [0.90827007, 0.10441282, 0.67690859],
       [0.50050105, 0.68891411, 0.3681635 ],
       [0.45032475, 0.57541791, 0.31299213],
       [0.6345716 , 0.75230832, 0.77656399]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Matrices

In [30]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a2[1]

array([4. , 5. , 6.5])

In [39]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [40]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [41]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [42]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4. Manipulating & Comparing Arrays

In [43]:
a1

array([1, 2, 3])

In [44]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [45]:
a1 + ones

array([2., 3., 4.])

In [46]:
a1 - ones

array([0., 1., 2.])

In [47]:
a1 * ones

array([1., 2., 3.])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [50]:
# How can you reshape a2 to be compatible with a3?

In [51]:
a1 / ones

array([1., 2., 3.])

In [52]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [53]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [54]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [55]:
a1 % 2 

array([1, 0, 1])

In [56]:
a1 / 2

array([0.5, 1. , 1.5])

In [57]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [58]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Aggregation = performing the same operation on a number of things

In [65]:
listy_list = [1,2,3]
type(listy_list)

list

In [61]:
sum(listy_list)

6

In [66]:
type(a1)

numpy.ndarray

In [63]:
np.sum(a1)

6

Use Python't methods (sum()) on Python datatypes and use
Use NumPy's methods (np.sum()) on NumPy arrays

In [70]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [71]:
massive_array[:10]

array([0.14629848, 0.02679954, 0.43896203, 0.21919162, 0.50924549,
       0.63324985, 0.09514576, 0.74406295, 0.24829088, 0.96799755])

In [72]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

3.75 ms ± 125 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
18.9 µs ± 72.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [73]:
np.mean(a2)

3.6333333333333333

In [74]:
np.max(a2)

6.5

In [75]:
np.min(a2)

1.0

In [76]:
# Standard deviation = squareroot of variance

np.std(a2)

1.8226964152656422

In [77]:
# Variance = measure of the average degree to which each number is different  from the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224