In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creatting Arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[7, 8, 0, 7, 5],
       [2, 9, 6, 0, 6],
       [3, 5, 5, 1, 9]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.97271141, 0.29787333, 0.96594986],
       [0.53171854, 0.2574188 , 0.27837112],
       [0.46965686, 0.62249772, 0.32423522],
       [0.01161416, 0.59398769, 0.1576314 ],
       [0.25826686, 0.25001859, 0.20882443]])

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.67841291, 0.4081817 , 0.02041821],
       [0.81758479, 0.88771495, 0.03091545],
       [0.06371184, 0.98514318, 0.31473821],
       [0.62331662, 0.41170544, 0.49330894],
       [0.44462142, 0.58950211, 0.69964794]])

In [27]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Matrices

In [29]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1. , 2. , 3.3])

In [35]:
a3.shape

(2, 3, 3)

In [36]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a2[1]

array([4. , 5. , 6.5])

In [38]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [41]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4. Manipulating & Comparing Arrays

In [42]:
a1

array([1, 2, 3])

In [43]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [44]:
a1 + ones

array([2., 3., 4.])

In [45]:
a1 - ones

array([0., 1., 2.])

In [46]:
a1 * ones

array([1., 2., 3.])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [49]:
# How can you reshape a2 to be compatible with a3?

In [50]:
a1 / ones

array([1., 2., 3.])

In [51]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [52]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [53]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [54]:
a1 % 2 

array([1, 0, 1])

In [55]:
a1 / 2

array([0.5, 1. , 1.5])

In [56]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [57]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Aggregation = performing the same operation on a number of things

In [58]:
listy_list = [1,2,3]
type(listy_list)

list

In [59]:
sum(listy_list)

6

In [60]:
type(a1)

numpy.ndarray

In [61]:
np.sum(a1)

6

Use Python't methods (sum()) on Python datatypes and use
Use NumPy's methods (np.sum()) on NumPy arrays

In [62]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [63]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [64]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

8.66 ms ± 2.04 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.6 µs ± 77.5 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [65]:
np.mean(a2)

3.6333333333333333

In [66]:
np.max(a2)

6.5

In [67]:
np.min(a2)

1.0

In [68]:
# Standard deviation = squareroot of variance

np.std(a2)

1.8226964152656422

In [69]:
# Variance = measure of the average degree to which each number is different  from the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [70]:
# Demo of std and va
high_var_array = np.array([1, 100, 200, 300, 400, 50000])
low_var_array = np.array([2,4,5,8,10])

In [71]:
np.var(high_var_array), np.var(low_var_array)

(344463833.47222227, 8.16)

In [72]:
np.std(high_var_array), np.std(low_var_array)

(18559.736891244505, 2.85657137141714)

In [73]:
np.mean(high_var_array), np.mean(low_var_array)

(8500.166666666666, 5.8)

Reshaping and Transposing

In [74]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [75]:
a2.shape

(2, 3)

In [76]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [77]:
a3.shape

(2, 3, 3)

In [78]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2_reshape = a2.reshape(2,3,1)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
# Transpose = switches the axis'
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [ ]:
a3.T.shape

(3, 3, 2)

## Dot Product

In [79]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [80]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [81]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [82]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [83]:
# Element-wise multipliocation (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [84]:
# Dot Product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [85]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [88]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [90]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])