In [3]:
import numpy as np

## DataTypes & Attributes

In [4]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creatting Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2,3))
ones

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,3))
zeros

In [26]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[1, 9, 7, 0, 0],
       [5, 1, 5, 4, 7],
       [6, 6, 0, 3, 1]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.95360403, 0.06082512, 0.44354568],
       [0.24857097, 0.54813029, 0.39385639],
       [0.34126264, 0.17159421, 0.93087496],
       [0.56524947, 0.72381309, 0.23202363],
       [0.65534618, 0.07402015, 0.77684021]])

In [35]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.33265584, 0.26902939, 0.86041056],
       [0.93797664, 0.6183265 , 0.93745784],
       [0.26691959, 0.7076285 , 0.57032596],
       [0.7295107 , 0.43954284, 0.18688233],
       [0.98920515, 0.50327551, 0.90351586]])

In [ ]:
# Pseudo-random numbers
np.random.seed()